targetPort = "2011"

[context.main]
	environment = {VITE_GQL_URI="https://sendmagnet.com"}

[context.staging]
	environment = { VITE_GQL_URI="https://staging-fulfillit-staging.kinsta.cloud" }
	 
[context.devolpment]
	environment = {VITE_GQL_URI="http://sendmagnet.local"}
	targetPort = "2011"

[[redirects]]
	from="/*"
	to="/index.html"
	status=200

